## Ejercicio 1

En la celda de código siguiente crea un dataframe llamado frutas que tenga esta estructura: 
<br><br>
<img src="imgs/ej-01.PNG">

In [93]:
import pandas as pd
frutas=pd.DataFrame({'Manzanas': [30], 'Platanos': [21]})
frutas

   Manzanas  Platanos
0        30        21

## Ejercicio 2

Crea un dataframe llamado ventas_frutas que encaje con la siguiente foto:

<br>

<img src="imgs/ej-01.2.PNG">

In [94]:
ventasFrutas=pd.DataFrame({'Manzanas': [35,41], 'Platanos': [21,34]}, index=['Ventas 2017','Ventas 2018'])
ventasFrutas

             Manzanas  Platanos
Ventas 2017        35        21
Ventas 2018        41        34

## Ejercicio 3

Crea una variable ingredientes que sea una serie con este contenido:

<img src="imgs/ej-01.3.PNG">

In [95]:
ingredientes=pd.Series(['4 Tazas', '1 Taza','2 unidades XL','1 Pieza'], index=['Harina','Leche','Huevos','Limon'], name='Cena')
ingredientes

Harina          4 Tazas
Leche            1 Taza
Huevos    2 unidades XL
Limon           1 Pieza
Name: Cena, dtype: str

## Ejercicio 4

Lee el dataset llamado **datos_casas_india.csv** que está en la ruta **datasets/datos_casas_india.csv** en una variable de tipo dataframe y llámalo casas_india, finalmente muestra su contenido.

In [96]:
datos_casas_indias=pd.read_csv("datasets/datos_casas_india.csv")
datos_casas_indias.head()
datos_casas_indias.shape

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/datos_casas_india.csv'

## Ejercicio 5

Ejecuta la siguiente celda para crear un dataframe llamado animales y crea una celda extra en la que se escriba ese dataframe en un fichero CSV en la ruta **datasets/animales.csv**

In [97]:
animales = pd.DataFrame({
    'nombre': ['perro', 'gato', 'conejo'],
    'edad': [5, 3, 2]
})

animales.to_csv('datasets/animales.csv')

OSError: Cannot save file into a non-existent directory: 'datasets'